# Generated by Django 4.1.3 on 2022-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(max_length=11),
        ),
    ]
