# Generated by Django 4.1.3 on 2022-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('classificacao', models.CharField(max_length=7)),
                ('lancamento', models.DateField()),
                ('direcao', models.CharField(max_length=30)),
                ('roteiro', models.CharField(max_length=100)),
                ('duracao_filme', models.DateTimeField()),
            ],
        ),
    ]
