# Generated by Django 4.1.3 on 2022-11-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name': 'Filme'},
        ),
    ]
