# Generated by Django 4.1.3 on 2022-12-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_categoria_alter_filmes_nome_filmes_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='classificacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='duracao_filme',
            field=models.FloatField(),
        ),
    ]
