# Generated by Django 4.1.3 on 2022-12-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_alter_filmes_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='duracao_filme',
            field=models.IntegerField(),
        ),
    ]
