# Generated by Django 4.1.3 on 2022-12-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_alter_filmes_duracao_filme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Filmes',
        ),
    ]
