# Generated by Django 4.1.3 on 2022-12-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RUIM'), (2, 'MEDIANO'), (3, 'BOM'), (4, 'MUITO BOM'), (5, 'EXCELENTE')]),
        ),
    ]
