# Generated by Django 4.1.3 on 2022-12-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0008_review_text_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
